---
sidebar: sidebar 
permalink: get-help.html 
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket 
summary: NetApp ofrece compatibilidad con Trident de distintas formas. Hay disponibles amplias opciones de auto-soporte gratuitas las 24 horas del día, los 7 días de la semana, como un canal Discord. 
---
= Soporte técnico
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ofrece compatibilidad con Astra Trident de muchas maneras. Hay disponibles amplias opciones de soporte gratuito las 24 horas del día, los 7 días de la semana, como artículos de la base de conocimiento (KB) y un canal Discord.



[[astra-trident-support-lifecycle]]
== Ciclo de vida del soporte de Astra Trident

Astra Trident proporciona tres niveles de soporte en función de su versión. Consulte link:https://mysupport.netapp.com/site/info/version-support["Compatibilidad con la versión del software NetApp para definiciones"^].

Soporte completo:: Astra Trident proporciona soporte completo durante doce meses a partir de la fecha de lanzamiento.
Soporte limitado:: Astra Trident ofrece un soporte limitado durante los meses entre 13 y 24 desde la fecha de lanzamiento.
Autosoporte:: La documentación de Astra Trident está disponible durante los meses 25 - 36, desde la fecha de lanzamiento.


[cols="1, 1, 1, 1"]
|===
| Versión | Soporte completo | Soporte limitado | Autosoporte 


 a| 
link:https://docs.netapp.com/us-en/trident-2310/index.html["23,10"^]
| -- | -- | Octubre de 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2307/index.html["23,07"^]
| -- | -- | Julio de 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2304/index.html["23,04"^]
| -- | -- | Abril de 2026 
|===

NOTE: Para conocer el calendario de soporte de la última versión de Trident, consulta la  https://docs.netapp.com/us-en/trident/get-help.html#trident-support-lifecycle["Página del ciclo de vida del soporte"].



[[self-support]]
== Autosoporte

Para obtener una lista completa de los artículos de solución de problemas, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes["Base de conocimientos de NetApp (se requiere inicio de sesión)"^]. También puede encontrar información sobre la solución de problemas relacionados con Astra https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra["aquí"^].



[[community-support]]
== Soporte de la comunidad

Existe una vibrante comunidad pública de usuarios de contenedores (incluidos los desarrolladores de Astra Trident) en Astra link:https://discord.gg/NetApp["Canal de discordia"^]. Este es un gran lugar para hacer preguntas generales sobre el proyecto y discutir temas relacionados con compañeros de ideas afines.



[[netapp-technical-support]]
== Soporte técnico de NetApp

Si necesita ayuda con Astra Trident, cree un paquete de soporte con `tridentctl logs -a -n trident` y envíelo a. `NetApp Support <Getting Help>`.



[[for-more-information]]
== Si quiere más información

* link:https://www.netapp.com/blog/["Blogs de Astra"^]
* link:https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Blogs de Astra Trident"^]
* link:https://www.netapp.com/console/["Kubernetes Hub"^]
* link:https://netapp.io/["NetApp.io"^]

